1

diff --git a/.github/workflows/test_new.yml b/.github/workflows/test_new.yml
--- a/.github/workflows/test_new.yml
+++ b/.github/workflows/test_new.yml
@@ -1,4 +1,4 @@
-name: test1
+name: Test Workflow
 
 on: 
   pull_request:
@@ -10,18 +10,32 @@ jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - name: Проверка репозитория
+      # Проверка репозитория
+      - name: Checkout Repository
         uses: actions/checkout@v3
-      - name: Настройка Python
+
+      # Настройка Python
+      - name: Set up Python
         id: setup-python
         uses: actions/setup-python@v4
         with:
           python-version: '3.12'
-      - name: Установка Pipenv
+
+      # Установка Pipenv
+      - name: Install Pipenv
         run: pip install pipenv
-      - name: Установка зависимостей с помощью Pipenv
-        run: pipenv install --dev
-      - name: Запуск тестов
+
+      # Вывод содержимого Pipfile для отладки
+      - name: Display Pipfile
+        run: cat Pipfile
+
+      # Установка зависимостей с помощью Pipenv
+      - name: Install Dependencies
+        run: |
+          pipenv install --dev || { echo 'Pipenv install failed'; exit 1; }
+
+      # Запуск тестов
+      - name: Run Tests
         run: |
           pipenv run pytest tests/
           pipenv run coverage report
